services:
  - type: web
    name: dronitor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: API_KEYS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dronitor-db
          property: connectionString

databases:
  - name: dronitor-db
    plan: free 